config_file_content: |
  [local]
  # port opened to listen for incoming connections from nodes
  node_port = 7070
  # port opened to listen for incoming connections from clients
  clients_port = 8080
  # port opened to listen for incoming connections from other load balancers (synchronization)
  load_balancer_port = 9090
  # interface used to communicate and re-route network packets to nodes
  net_interface_nodes = "eth1"
  # interface used to retrieve and re-route network packets from clients 
  net_interface_clients = "eth1"
  
  [node_health]
  # number of continuous health checks that must be passed before being eligible for routing destination
  checks_before_routing = 3
  # duration of deadline between health checks, after this period, nodes will be removed from the routing ring
  checks_timeout = "5s"
  
  # number of times nodes can fail to send health checks before they are blacklisted
  # ex: the node will be added and removed 5 times to the routing table before they will start to be completly ignored.
  # use -1 if want to disable this option
  black_list_after_fails = 5
  
  # duration of the ban
  black_list_expiry = "5m"
  
  [load_balancer_quorum]
  # enforce_single_configuration is used to enforce that all load balancers must have the same configuration regarding
  # nodes (ex: node health timeout). If this option is set to true, the load balancers will have to contain the same
  # parameters in order to reach consensus. If a load balancer tries to connect with a different configuration, it will
  # be ignored
  enforce_single_configuration = false
  
  addresses = [
      { ip = "192.168.1.1", port = 9090 },
      { ip = "192.168.1.2", port = 9090 },
      { ip = "192.168.1.3", port = 9090 }
  ]